  rule-providers:
    reject_non_ip_drop:
      type: http
      behavior: classical
      format: text
      interval: 43200
      url: https://ruleset.skk.moe/Clash/non_ip/reject-drop.txt
      path: ./sukkaw_ruleset/reject_non_ip_drop.txt
    reject_non_ip:
      type: http
      behavior: classical
      format: text
      interval: 43200
      url: https://ruleset.skk.moe/Clash/non_ip/reject.txt
      path: ./sukkaw_ruleset/reject_non_ip.txt
    reject_ip:
      type: http
      behavior: classical
      format: text
      interval: 43200
      url: https://ruleset.skk.moe/Clash/ip/reject.txt
      path: ./sukkaw_ruleset/reject_ip.txt
    ai_non_ip:
      type: http
      behavior: domain
      format: text
      interval: 43200
      url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
      path: ./sukkaw_ruleset/ai_non_ip.txt
    microsoft_cdn_non_ip:
      type: http
      behavior: classical
      format: text
      interval: 43200
      url: https://ruleset.skk.moe/Clash/non_ip/microsoft_cdn.txt
      path: ./sukkaw_ruleset/microsoft_cdn_non_ip.txt
    microsoft_non_ip:
      type: http
      behavior: classical
      format: text
      interval: 43200
      url: https://ruleset.skk.moe/Clash/non_ip/microsoft.txt
      path: ./sukkaw_ruleset/microsoft_non_ip.txt
    download_domainset:
      type: http
      behavior: domain
      format: text
      interval: 43200
      url: https://ruleset.skk.moe/Clash/domainset/download.txt
      path: ./sukkaw_ruleset/download_domainset.txt
    download_non_ip:
      type: http
      behavior: domain
      format: text
      interval: 43200
      url: https://ruleset.skk.moe/Clash/non_ip/download.txt
      path: ./sukkaw_ruleset/download_non_ip.txt